from datetime import date
from typing import Dict, List


def _build_laws_section(statute_summaries: List[Dict]) -> str:
    if not statute_summaries:
        return (
            "**No statutes listed**\n"
            "No statute summaries were provided in this mock run. "
            "A licensed attorney can assess which laws may apply.\n"
        )

    blocks = []
    for statute in statute_summaries:
        name = statute.get("statute_name", "Unknown Statute")
        citation = statute.get("citation", "Citation unavailable")
        summary = statute.get("plain_language_summary", "Summary unavailable.")
        sol = statute.get("statute_of_limitations", "Unknown")
        sol_notes = statute.get("sol_notes", "No additional limitations notes provided.")
        blocks.append(
            f"**{name} ({citation})**\n"
            f"{summary} A licensed attorney can assess whether this law applies to your situation.\n"
            f"Claims under this statute are generally subject to a {sol} statute of limitations, "
            f"though this varies. {sol_notes}\n"
        )
    return "\n".join(blocks)


def _build_referrals_section(results: List[Dict]) -> str:
    if not results:
        return (
            "**No organizations found in mock data**\n"
            "Call **211** (dial 2-1-1) and ask for emergency legal assistance.\n"
        )

    org_blocks = []
    for org in results:
        org_blocks.append(
            f"**{org.get('org_name', 'Unknown Organization')}**\n"
            f"📍 {org.get('address', 'Unknown location')}\n"
            f"📞 {org.get('phone', 'Phone unavailable')}\n"
            f"🌐 {org.get('website', 'Website unavailable')}\n"
            f"Serves: {', '.join(org.get('issue_types', [])) or 'Not specified'}\n"
            f"Eligibility: {org.get('eligibility_notes', 'Not specified')}\n"
            f"Intake: {org.get('intake_process', 'Not specified')}\n"
        )
    return "\n".join(org_blocks)


def generate_intake_doc(context: dict) -> str:
    classification = context.get("classification", {})
    jurisdiction_data = context.get("jurisdiction", {})
    jurisdiction = jurisdiction_data.get("jurisdiction", {})
    statute_summaries = context.get("statute_summaries", [])
    referrals = context.get("referrals", {})
    referral_results = referrals.get("results", [])

    issue_type = classification.get("primary_domain", "Not specified")
    sub_type = classification.get("sub_type", "Not specified")
    urgency = classification.get("urgency", "medium")
    city = jurisdiction.get("city") or "Not specified"
    state = jurisdiction.get("state") or "Not specified"
    user_input = context.get("user_input", "No user description provided.")

    laws_section = _build_laws_section(statute_summaries)
    referrals_section = _build_referrals_section(referral_results)

    urgency_block = ""
    if urgency in {"high", "critical"}:
        self_help_url = (
            jurisdiction_data.get("court_info", {}).get("self_help_url")
            or "state court self-help center website"
        )
        urgency_block = (
            "\n## If You Have an Urgent Deadline\n\n"
            "Your situation may involve an imminent deadline. Contact one of the organizations\n"
            "above immediately and mention your deadline when you call. If you cannot reach\n"
            "them, call **211** (dial 2-1-1) and ask for emergency legal assistance, or visit\n"
            f"the {state} court self-help center at {self_help_url}.\n"
        )

    return (
        "---\n"
        "⚠️ THIS DOCUMENT IS NOT LEGAL ADVICE.\n"
        "It was generated by an automated triage tool to help you prepare for a consultation\n"
        "with a licensed attorney. Only a licensed attorney can give you legal advice about\n"
        "your specific situation.\n"
        f"Generated: {date.today().isoformat()}\n"
        "---\n\n"
        "# Legal Aid Intake Summary\n\n"
        "## Situation Overview\n\n"
        f"The user describes a situation in which {user_input}\n\n"
        "## Key Details\n\n"
        "| Field | Information |\n"
        "|-------|-------------|\n"
        f"| Issue Type | {issue_type} - {sub_type} |\n"
        f"| Jurisdiction | {city}, {state} |\n"
        f"| Urgency | {urgency} |\n"
        "| Situation Start | Not specified |\n"
        "| Parties Involved | Employer; employee |\n"
        "| Documents in Hand | None mentioned |\n\n"
        "## Potentially Relevant Laws\n\n"
        f"{laws_section}\n"
        "## Documents to Gather Before Your Consultation\n\n"
        "- [ ] Pay stubs and wage statements\n"
        "- [ ] Offer letter or employment agreement\n"
        "- [ ] Termination or disciplinary notices\n"
        "- [ ] Email or text communications with employer\n"
        "- [ ] Time records and scheduling logs\n\n"
        "## Questions to Ask Your Attorney\n\n"
        "- What filing deadlines apply to these employment claims in this state?\n"
        "- Which documents are most important to prioritize before intake?\n"
        "- Should any agency complaint be filed before other legal steps?\n"
        "- What evidence is most useful for unpaid wage and retaliation issues?\n"
        "- Are there likely costs or fee waivers for this process?\n"
        "- What should I track now to preserve a clear timeline?\n\n"
        "## Legal Aid Organizations Near You\n\n"
        f"{referrals_section}"
        "\n---\n"
        f"{urgency_block}"
        "\n⚠️ THIS DOCUMENT IS NOT LEGAL ADVICE.\n"
        "Only a licensed attorney can advise you on your specific situation.\n"
    )
